Pandas
- Fast, flexible, and designed to work with tabular data.
- Designed to make work easier with structured data.

--- Robust for loading the data from files like CSV, Excel etc.

--- Easy handling of any kind of missing values in the data (NaN Values)

--- Size Mutability: Columns can be inserted and deleted

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.__version__

'2.1.4'

In [ ]:
# Pandas Dataframe - A two-D Structure where data is aligned in a tabular form.

In [ ]:
#First series of df(DataFrame)
data = np.array(['a','b','c','d'])
s1 = pd.Series(data)
print(s1)

0    a
1    b
2    c
3    d
dtype: object

In [ ]:
num_series = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(num_series)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
#First Pandas DataFrame
two_d = np.random.randint(5,10, (3,4))
first_df = pd.DataFrame(two_d, columns = ["a", "b", "c", "d"])
print(first_df)

   a  b  c  d
0  6  9  6  5
1  5  5  6  8
2  5  7  6  5

In [ ]:
two_d = np.random.randint(10,35, (3,4))
hello_df = pd.DataFrame(two_d, columns = ["a", "b", "c", "d"], index = ["A", "B", "C"])
print(hello_df)
#

    a   b   c   d
A  13  14  33  15
B  34  26  32  23
C  28  12  19  29

In [ ]:
num_series = pd.Series([1,2,3,4,5,6], index = ['a','b','c','d','e','f'], name = "Number")
df = pd.DataFrame(num_series)
print(df)

   Number
a       1
b       2
c       3
d       4
e       5
f       6

In [ ]:
dilip_fav = np.random.randint(10,35, (3,4))
dilip_df = pd.DataFrame(dilip_fav, columns = ["a", "b", "c", "d"], index = ["English", "Telugu", "Social"])
print(dilip_df)

          a   b   c   d
English  23  19  24  17
Telugu   22  14  13  15
Social   18  29  25  13

In [ ]:
# prompt: create a dataframe with 2 columns and 10 rows

import pandas as pd
import numpy as np

data = np.random.rand(10, 2)  # Generate random data
df = pd.DataFrame(data, columns=['Column1', 'Column2'])
print(df)

    Column1   Column2
0  0.630017  0.381914
1  0.681989  0.153395
2  0.734926  0.897958
3  0.220032  0.300218
4  0.965603  0.784941
5  0.476778  0.287787
6  0.869150  0.906831
7  0.569745  0.547062
8  0.076127  0.822950
9  0.616582  0.499658

In [ ]:
list_of_lists = [["Dilip", 24], ["Vasu", 2], ["Neimisha", 27]]
df = pd.DataFrame(list_of_lists, columns = ["Name", "Age"], index = (1,2,3))
print(df)

       Name  Age
1     Dilip   24
2      Vasu    2
3  Neimisha   27

In [ ]:
employee_dict = {"Employee Name": ["Dilip", "Vasu", "Neimisha", "Kishore"], "Age": [24, 2, 27, 31], "Income $": [65000,
                                                                                                               55000, 60000, 85000]}
df = pd.DataFrame(employee_dict)
print(df)

  Employee Name  Age  Income $
0         Dilip   24     65000
1          Vasu    2     55000
2      Neimisha   27     60000
3       Kishore   31     85000

In [ ]:
series_dict = {"First Series": pd.Series([1,2,3,4]), "Second Series": pd.Series([5,6,7,8])}
df = pd.DataFrame(series_dict)
print(df)

   First Series  Second Series
0             1              5
1             2              6
2             3              7
3             4              8

In [ ]:
list_of_dict = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]
df = pd.DataFrame(list_of_dict, index = (1,2))
print(df)

   a   b     c
1  1   2   NaN
2  5  10  20.0

In [ ]:
list_a = ["Guntur Kaaram", "Khaleja", "Athadu"]
list_b = ["1", "Businessman", "Pokiri"]
list_of_tuples = list(zip(list_a, list_b))
#print(list_of_tuples)
df = pd.DataFrame(list_of_tuples, columns = ["MBx3V", "MBxPuri"], index = (1,2,3))
print(df)

           MBx3V      MBxPuri
1  Guntur Kaaram            1
2        Khaleja  Businessman
3         Athadu       Pokiri

In [ ]:
#Create a DataFrame with 100 rows and 5 Different columns
our_array = np.random.randn(100,5)
#print(our_array)
df = pd.DataFrame(our_array, columns = ["a", "b", "c", "d", "e"])
print(df)

           a         b         c         d         e
0   1.135128 -0.389427  0.069412  1.025060  1.095139
1  -0.353668  1.751153 -0.281406 -1.042236 -0.713194
2   0.434388  0.942609  0.847914 -1.481112  1.203859
3  -0.838867 -1.523949 -0.670761 -1.196524  0.623472
4  -0.783075 -0.694598 -0.232646 -0.317736  0.054314
..       ...       ...       ...       ...       ...
95 -1.015670 -0.374060 -0.840605  0.023194  1.332374
96  0.418332  1.260845  0.145041 -1.585094 -1.749945
97  1.206349 -1.196643 -1.715666  0.781166  0.709814
98  1.174557  0.042321  0.441976  0.041867 -0.606838
99 -0.757022  0.409584  0.216632 -1.102426  0.619365

[100 rows x 5 columns]

In [ ]:
df.head()

          a         b         c         d         e
0  1.135128 -0.389427  0.069412  1.025060  1.095139
1 -0.353668  1.751153 -0.281406 -1.042236 -0.713194
2  0.434388  0.942609  0.847914 -1.481112  1.203859
3 -0.838867 -1.523949 -0.670761 -1.196524  0.623472
4 -0.783075 -0.694598 -0.232646 -0.317736  0.054314

In [ ]:
df.head(10)

          a         b         c         d         e
0  1.135128 -0.389427  0.069412  1.025060  1.095139
1 -0.353668  1.751153 -0.281406 -1.042236 -0.713194
2  0.434388  0.942609  0.847914 -1.481112  1.203859
3 -0.838867 -1.523949 -0.670761 -1.196524  0.623472
4 -0.783075 -0.694598 -0.232646 -0.317736  0.054314
5  0.757774 -0.308014  0.072281  0.419737 -0.214242
6 -0.575826  0.404360  0.964738  0.876069 -1.308593
7  0.374758  0.752128  2.068971 -1.167135  1.394655
8  0.479973 -1.136332  1.375154  1.229343  0.196209
9 -1.521759 -0.397597  3.171378 -0.633033  0.739386

In [ ]:
df.tail()

           a         b         c         d         e
95 -1.015670 -0.374060 -0.840605  0.023194  1.332374
96  0.418332  1.260845  0.145041 -1.585094 -1.749945
97  1.206349 -1.196643 -1.715666  0.781166  0.709814
98  1.174557  0.042321  0.441976  0.041867 -0.606838
99 -0.757022  0.409584  0.216632 -1.102426  0.619365

In [ ]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       100 non-null    float64
 1   b       100 non-null    float64
 2   c       100 non-null    float64
 3   d       100 non-null    float64
 4   e       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB

In [ ]:
df.shape

(100, 5)

In [ ]:
df.rename(columns = {"a": "A", "b": "B", "c": "C", "d": "D", "e": "E"})

           A         B         C         D         E
0   1.135128 -0.389427  0.069412  1.025060  1.095139
1  -0.353668  1.751153 -0.281406 -1.042236 -0.713194
2   0.434388  0.942609  0.847914 -1.481112  1.203859
3  -0.838867 -1.523949 -0.670761 -1.196524  0.623472
4  -0.783075 -0.694598 -0.232646 -0.317736  0.054314
..       ...       ...       ...       ...       ...
95 -1.015670 -0.374060 -0.840605  0.023194  1.332374
96  0.418332  1.260845  0.145041 -1.585094 -1.749945
97  1.206349 -1.196643 -1.715666  0.781166  0.709814
98  1.174557  0.042321  0.441976  0.041867 -0.606838
99 -0.757022  0.409584  0.216632 -1.102426  0.619365

[100 rows x 5 columns]

In [ ]:
df.head()

          a         b         c         d         e
0  1.135128 -0.389427  0.069412  1.025060  1.095139
1 -0.353668  1.751153 -0.281406 -1.042236 -0.713194
2  0.434388  0.942609  0.847914 -1.481112  1.203859
3 -0.838867 -1.523949 -0.670761 -1.196524  0.623472
4 -0.783075 -0.694598 -0.232646 -0.317736  0.054314

In [2]:
#Importing dataset into Colab
path = "/content/Ecommerce Customers.csv"
df = pd.read_csv(path)

In [3]:
df.head()

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092

In [4]:
imdb_df = pd.read_csv("/content/imdb_data.csv")

In [5]:
imdb_df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [6]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [7]:
df.describe()

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
count,500.000000,500.000000,500.000000,500.000000,500.000000
mean,33.053194,12.052488,37.060445,3.533462,499.314038
std,0.992563,0.994216,1.010489,0.999278,79.314782
min,29.532429,8.508152,33.913847,0.269901,256.670582
25%,32.341822,11.388153,36.349257,2.930450,445.038277
50%,33.082008,11.983231,37.069367,3.533975,498.887875
75%,33.711985,12.753850,37.716432,4.126502,549.313828
max,36.139662,15.126994,40.005182,6.922689,765.518462

In [8]:
imdb_df.describe()

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [9]:
#Indexing & Slicing
#loc method & iloc() method
imdb_df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

iloc() Method

In [10]:
df.iloc[1:8, 2:5]

             Avatar  Avg. Session Length  Time on App
1         DarkGreen            31.926272    11.109461
2            Bisque            33.000915    11.330278
3       SaddleBrown            34.305557    13.717514
4  MediumAquaMarine            33.330673    12.795189
5       FloralWhite            33.871038    12.026925
6     DarkSlateBlue            32.021596    11.366348
7              Aqua            32.739143    12.351959

In [11]:
imdb_df.iloc[1:8, 2:5]

,budget,genres,homepage
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN
2,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/
3,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/
4,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN
5,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN
6,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/
7,0,"[{'id': 99, 'name': 'Documentary'}]",NaN

In [12]:
imdb_df.iloc[:, -3:]

,cast,crew,revenue
0,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...
2995,"[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,"[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,"[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,"[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,"[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [15]:
imdb_df.iloc[50:60, 7:12]

,original_title,overview,popularity,poster_path,production_companies
50,Aanrijding in Moscou,‘Moscou’ is a densely populated working class ...,1.572904,/bDZSLsqrpUhdjSVXYGKwiOrLlEb.jpg,NaN
51,The Great Race,"Professional daredevil and white-suited hero, ...",4.473327,/nc6FRAVC4a8o4podiFy2P5qI9ul.jpg,"[{'name': 'Warner Bros.', 'id': 6194}]"
52,The Last Flight of Noah's Ark,The only chance to escape a desert island is t...,1.012665,/undK2bf6ntIt7gTMjX9KkzeXSTU.jpg,"[{'name': 'Walt Disney Productions', 'id': 3166}]"
53,For Keeps,"Darcy, editor at her highschool paper, and her...",5.410839,/h413LQAMIwYyyw8lJffMpDcyC5A.jpg,"[{'name': 'TriStar Pictures', 'id': 559}]"
54,Risen,Follows the epic Biblical story of the Resurre...,8.759801,/cr8lQd94bxlhyDfimweUMnLZoxf.jpg,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam..."
55,Son in Law,Country girl Rebecca has spent most of her lif...,9.122718,/zVnzFkQqcPC1uxhAuIaWx4H0kEO.jpg,"[{'name': 'Hollywood Pictures', 'id': 915}]"
56,Joueuse,"In a small Corsican village, the life of Hélèn...",2.947980,/qF1FUaqh6GPN5xXp030op4r5O26.jpg,"[{'name': 'Mon Voisin Productions', 'id': 22983}]"
57,Batman & Robin,Along with crime-fighting partner Robin and ne...,17.038824,/79AYCcxw3kSKbhGpx1LiqaCAbwo.jpg,"[{'name': 'PolyGram Filmed Entertainment', 'id..."
58,Were The World Mine,"If you had a love-potion, who would you make f...",1.882446,/sE3Tn6B8tfbDk7ctFzHLH082r43.jpg,"[{'name': 'Speak Productions', 'id': 3599}]"
59,All About the Benjamins,Bucum Jackson (Cube) is a bounty hunter with a...,3.909079,/MnD3ueM3Kh6mxTT9oqw9fhxSzd.jpg,"[{'name': 'New Line Cinema', 'id': 12}]"

In [16]:
#loc() method
imdb_df.loc[50:60, ["budget","genres","runtime"]]

       budget                                             genres  runtime
50     560000  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...    102.0
51   12000000  [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...    160.0
52          0  [{'id': 12, 'name': 'Adventure'}, {'id': 10751...     97.0
53          0  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...     98.0
54   20000000                     [{'id': 28, 'name': 'Action'}]    107.0
55          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     95.0
56          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     97.0
57  125000000  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...    125.0
58          0  [{'id': 10402, 'name': 'Music'}, {'id': 10749,...     95.0
59   14000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...     95.0
60  150000000  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...    144.0

In [19]:
imdb_df.loc[:, ["budget","genres","runtime"]]

        budget                                             genres  runtime
0     14000000                     [{'id': 35, 'name': 'Comedy'}]     93.0
1     40000000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    113.0
2      3300000                      [{'id': 18, 'name': 'Drama'}]    105.0
3      1200000  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...    122.0
4            0  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...    118.0
...        ...                                                ...      ...
2995         0  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...    102.0
2996         0  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...    102.0
2997  65000000  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...    120.0
2998  42000000  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...     90.0
2999  35000000  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...    106.0

[3000 rows x 3 columns]

In [21]:
imdb_df.loc[:, "budget"]

0       14000000
1       40000000
2        3300000
3        1200000
4              0
          ...
2995           0
2996           0
2997    65000000
2998    42000000
2999    35000000
Name: budget, Length: 3000, dtype: int64

In [22]:
new_df = imdb_df.loc[10:20, ["budget","genres","runtime"]]

In [23]:
new_df.head()

       budget                                             genres  runtime
10    1000000                      [{'id': 18, 'name': 'Drama'}]    119.0
11          0                     [{'id': 35, 'name': 'Comedy'}]     98.0
12   15000000                      [{'id': 18, 'name': 'Drama'}]    122.0
13   53000000  [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...    118.0
14  102000000  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...    145.0

In [30]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [31]:
imdb_df["original_title"]

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                           마린보이
                          ...
2995                                     Chasers
2996                                 Vi är bäst!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: original_title, Length: 3000, dtype: object

In [25]:
imdb_df["original_language"] == "en"

0        True
1        True
2        True
3       False
4       False
        ...
2995     True
2996    False
2997     True
2998     True
2999     True
Name: original_language, Length: 3000, dtype: bool

In [26]:
english_movies = imdb_df[imdb_df["original_language"] == "en"]

In [29]:
english_movies

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [32]:
other_movies = imdb_df[imdb_df["original_language"] != "en"]
other_movies

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
15,16,NaN,500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://skinningmovie.com/synopsis.htm,tt1129437,sr,Šišanje,Novica is a mathematics champion in a Belgrade...,1.018477,...,10/6/10,97.0,"[{'iso_639_1': 'sr', 'name': 'Srpski'}]",Released,Life is sometimes rude game: one mistake can b...,Skinning,"[{'id': 379, 'name': 'skinhead'}, {'id': 7492,...","[{'cast_id': 1001, 'character': 'Novica', 'cre...","[{'credit_id': '52fe4927c3a36847f818bb5f', 'de...",198
30,31,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1675434,fr,Intouchables,A true story of two men who should never have ...,16.086919,...,11/2/11,112.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes you have to reach into someone else'...,The Intouchables,"[{'id': 3230, 'name': 'male friendship'}, {'id...","[{'cast_id': 6, 'character': 'Philippe', 'cred...","[{'credit_id': '52fe4967c3a368484e129b63', 'de...",426480871
31,32,NaN,0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...",http://www.cache-derfilm.at,tt0387898,fr,Caché,A married couple is terrorized by a series of ...,5.695860,...,5/2/05,117.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Caché,"[{'id': 90, 'name': 'paris'}, {'id': 213, 'nam...","[{'cast_id': 2, 'character': 'Georges Laurent'...","[{'credit_id': '52fe4244c3a36847f8011073', 'de...",36000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2963,2964,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",http://www.koizora-movie.jp,tt1194664,ja,恋空,"During her freshman year in high school, Mika ...",1.718237,...,11/3/07,129.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Sky Of Love,"[{'id': 6270, 'name': 'high school'}, {'id': 9...","[{'cast_id': 1, 'character': 'Tahara Mika', 'c...","[{'credit_id': '52fe459fc3a36847f80d161b', 'de...",44038000
2972,2973,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0482930,cn,龍虎門,Dragon Tiger Gate is a 2006 Hong Kong martial ...,4.154861,...,7/27/06,94.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}]",Released,NaN,Dragon Tiger Gate,"[{'id': 780, 'name': 'kung fu'}]","[{'cast_id': 1, 'character': 'Dragon Wong', 'c...","[{'credit_id': '52fe46869251416c7507b08f', 'de...",8685526
2980,2981,NaN,300000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",https://www.facebook.com/Actionherobiju/,tt5320514,ml,ആക്ഷൻ ഹീറോ ബിജു,Biju is an honest policeman who fights the inj...,0.350207,...,2/4/16,144.0,"[{'iso_639_1': 'ml', 'name': ''}]",Released,A ride with a police officer,Action Hero Biju,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 1, 'character': 'Sub-Inspector Bi...","[{'credit_id': '56b4d47f92514112b90045f6', 'de...",2500000
2988,2989,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0301978,fa,ده,A visual social examination in the form of ten...,0.984515,...,5/20/02,94.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Ten,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 2, 'character': 'Driver', 'credit...","[{'credit_id': '52fe460a9251416c7506b0a7', 'de...",105656
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590

In [33]:
runtime = imdb_df[imdb_df["runtime"] > 120]
runtime

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,American Beauty,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The system is perfect until it comes after you.,Minority Report,"[{'id': 476, 'name': 'self-fulfilling prophecy...","[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926
20,21,NaN,80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,tt0120738,en,Lost in Space,The prospects for continuing life on Earth in ...,12.000579,...,4/3/98,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Danger, Will Robinson!",Lost in Space,"[{'id': 4379, 'name': 'time travel'}, {'id': 1...","[{'cast_id': 26, 'character': 'Dr. Zachary Smi...","[{'credit_id': '52fe433bc3a36847f80448b9', 'de...",136159423
33,34,"[{'id': 207632, 'name': 'The ABCs of Death Col...",0,"[{'id': 27, 'name': 'Horror'}]",NaN,tt2926810,en,ABCs of Death 2,Taking all that was great from the first insta...,8.254856,...,10/2/14,125.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Some people never learn,ABCs of Death 2,"[{'id': 9706, 'name': 'anthology'}, {'id': 187...","[{'cast_id': 60, 'character': 'Assassin (Segme...","[{'credit_id': '52fe4cd69251416c91101d73', 'de...",7171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2969,2970,NaN,19800000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,tt0280707,en,Gosford Park,"Multiple storylined drama set in 1932, showing...",14.101101,...,11/7/01,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Tea at four. Dinner at eight. Murder at midnight.,Gosford Park,"[{'id': 964, 'name': 'servant'}, {'id': 10594,...","[{'cast_id': 2, 'character': 'Mrs. Wilson', 'c...","[{'credit_id': '52fe4401c3a36847f807ceab', 'de...",87754044
2970,2971,NaN,25000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",NaN,tt0103855,en,The Bodyguard,A former Secret Service agent grudgingly takes...,9.805017,...,11/25/92,129.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Never let her out of your sight. Never let you...,The Bodyguard,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 17, 'character': 'Rachel Marron',...","[{'credit_id': '52fe425ec3a36847f8019133', 'de...",411006740
2980,2981,NaN,300000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",https://www.facebook.com/Actionherobiju/,tt5320514,ml,ആക്ഷൻ ഹീറോ ബിജു,Biju is an honest policeman who fights the inj...,0.350207,...,2/4/16,144.0,"[{'iso_639_1': 'ml', 'name': ''}]",Released,A ride with a police officer,Action Hero Biju,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 1, 'character': 'Sub-Inspector Bi...","[{'credit_id': '56b4d47f92514112b90045f6', 'de...",2500000
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,3/18/24,149.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,"""Happiness Must Be Earned""",The Thief of Bagdad,"[{'id': 255, 'name': 'male nudity'}, {'id': 14...","[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,The Terminal,"[{'id': 242, 'name': 'new york'}, {'id': 822, ...","[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255